/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.airline;

/**
 *
 * @author HP
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWelcome = new javax.swing.JPanel();
        jLLM = new javax.swing.JLabel();
        jLMSS1 = new javax.swing.JLabel();
        jLLogo = new javax.swing.JLabel();
        myProgress = new javax.swing.JProgressBar();
        Percentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelWelcome.setBackground(new java.awt.Color(255, 255, 255));

        jLLM.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLLM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLLM.setText("Loading Modules...");

        jLMSS1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        jLMSS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMSS1.setText("Airline System");

        jLLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Percentage.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        Percentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Percentage.setText("%");

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLLM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 346, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLMSS1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLM)
                    .addComponent(Percentage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLMSS1)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        WelcomePage welcome = new WelcomePage();
        welcome.setVisible(true);
        try{
            for(int i=0; i<=100; i++)
            {
                Thread.sleep(40);
                welcome.myProgress.setValue(i);
                welcome.Percentage.setText(Integer.toString(i)+"%");
                         
            }       
        }catch (Exception e){   
        }
        new LogIn().setVisible(true);
        welcome.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Percentage;
    private javax.swing.JLabel jLLM;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLMSS1;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JProgressBar myProgress;
    // End of variables declaration//GEN-END:variables
}
